### ISSUE TITLE
Breaking dynamic components

### ISSUE THREAD

**Issue by defaye** [mmoollllee/nuxt-protected-mailto#6]
Your plugin seems to be making my `.nuxt/components/index.js` build in a different way that is causing my app to kick out `Nuxt: [Vue warn]: Unknown custom element <Foo> - did you register the component correctly?` all over.

**Comment by CodingWithNuke** [comment]
The same thing happens to me.

One enabling the module, it breaks `nuxt/components`.

**Comment by mmoollllee** [comment]
Should be fixed with current release. Can you confirm?

**Comment by CodingWithNuke** [comment]
> Thanks for reporting! Should be fixed with current release. Can you confirm?

Seems to be working perfectly!
